version: '3'

volumes:
  db-data:

services:
  db:
    image: postgres:12
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
  api:
    build: .
    command: > 
      sh -c "
      rails db:create &&
      rails db:migrate &&
      rm -f tmp/pids/server.pid && 
      bundle exec rails s -p 3001 -b '0.0.0.0'
      "
    volumes:
      - .:/myapp
    environment:
      - 'DATABASE_PASSWORD=postgres'
    tty: true  
    stdin_open: true
    ports:
      - "3001:3001"
    depends_on:
      - db
    links:
      - db

 